# Generated by Django 4.2.5 on 2023-11-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='activities',
        ),
        migrations.AddField(
            model_name='tags',
            name='activities',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='core.activities'),
        ),
    ]
