# Generated by Django 4.2.5 on 2023-11-20 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_tags_activities_tags_activities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionitems',
            old_name='action_items',
            new_name='action_item',
        ),
        migrations.AlterField(
            model_name='intentions',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intentions', to='core.activities'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='activities',
            field=models.ManyToManyField(related_name='tags', to='core.activities'),
        ),
    ]
