# Generated by Django 4.2.5 on 2023-11-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='journal_name',
            field=models.CharField(blank=True, default='Untitled', max_length=200, null=True),
        ),
    ]
