# Generated by Django 4.2.5 on 2023-11-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_journal_journal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='tags', to='core.activities'),
        ),
    ]
