# Generated by Django 4.2.5 on 2023-11-23 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_tags_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='current_table',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journaltables',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_tables', to='core.journal'),
        ),
    ]
