# Generated by Django 4.2.5 on 2023-11-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_actionitems_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='name',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
