# Generated by Django 4.2.5 on 2023-12-02 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_actionitems_ordering_activities_ordering_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionitems',
            options={'ordering': ['ordering']},
        ),
        migrations.AlterModelOptions(
            name='activities',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='gratefulfor',
            options={'ordering': ['ordering']},
        ),
        migrations.AlterModelOptions(
            name='happenings',
            options={'ordering': ['ordering']},
        ),
        migrations.AlterModelOptions(
            name='intentions',
            options={'ordering': ['ordering']},
        ),
    ]
