# Generated by Django 4.2.5 on 2023-12-03 03:16

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_actionitems_options_alter_activities_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activities',
            options={'ordering': ['ordering']},
        ),
        migrations.AlterField(
            model_name='journaltables',
            name='table_name',
            field=models.CharField(blank=True, default=core.models.create_default_table_name, max_length=100, null=True),
        ),
    ]
