# Generated by Django 4.2.5 on 2023-12-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_activities_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journaltables',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='journaltables',
            name='table_func',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
