# Generated by Django 4.2.5 on 2023-12-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_journaltables_table_func'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journaltables',
            name='table_func',
        ),
        migrations.AddField(
            model_name='journal',
            name='journal_table_func',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
