# Generated by Django 4.2.5 on 2024-09-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_journaltables_table_func_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionitems',
            options={'ordering': ['ordering'], 'verbose_name': 'ActionItem', 'verbose_name_plural': 'ActionItems'},
        ),
        migrations.AlterModelOptions(
            name='activities',
            options={'ordering': ['ordering'], 'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='gratefulfor',
            options={'ordering': ['ordering'], 'verbose_name': 'GratefulFor', 'verbose_name_plural': 'GratefulFor'},
        ),
        migrations.AlterModelOptions(
            name='happenings',
            options={'ordering': ['ordering'], 'verbose_name': 'Happening', 'verbose_name_plural': 'Happenings'},
        ),
        migrations.AlterModelOptions(
            name='intentions',
            options={'ordering': ['ordering'], 'verbose_name': 'Intention', 'verbose_name_plural': 'Intentions'},
        ),
        migrations.AlterModelOptions(
            name='journal',
            options={'verbose_name': 'Journal', 'verbose_name_plural': 'Journals'},
        ),
        migrations.AlterModelOptions(
            name='journaltables',
            options={'ordering': ['id'], 'verbose_name': 'JournalTable', 'verbose_name_plural': 'JournalTables'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='activities',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
